/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BankruptcyRouteImport } from './routes/bankruptcy'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedPortalCreditRouteImport } from './routes/_authenticated/portal.credit'
import { Route as AuthenticatedPortalBankruptcyRouteImport } from './routes/_authenticated/portal.bankruptcy'
import { Route as AuthenticatedPortalCreditVerificationRouteImport } from './routes/_authenticated/portal.credit.verification'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BankruptcyRoute = BankruptcyRouteImport.update({
  id: '/bankruptcy',
  path: '/bankruptcy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalCreditRoute =
  AuthenticatedPortalCreditRouteImport.update({
    id: '/credit',
    path: '/credit',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalBankruptcyRoute =
  AuthenticatedPortalBankruptcyRouteImport.update({
    id: '/bankruptcy',
    path: '/bankruptcy',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalCreditVerificationRoute =
  AuthenticatedPortalCreditVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedPortalCreditRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bankruptcy': typeof BankruptcyRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/portal/bankruptcy': typeof AuthenticatedPortalBankruptcyRoute
  '/portal/credit': typeof AuthenticatedPortalCreditRouteWithChildren
  '/portal/credit/verification': typeof AuthenticatedPortalCreditVerificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bankruptcy': typeof BankruptcyRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/portal/bankruptcy': typeof AuthenticatedPortalBankruptcyRoute
  '/portal/credit': typeof AuthenticatedPortalCreditRouteWithChildren
  '/portal/credit/verification': typeof AuthenticatedPortalCreditVerificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/bankruptcy': typeof BankruptcyRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/portal/bankruptcy': typeof AuthenticatedPortalBankruptcyRoute
  '/_authenticated/portal/credit': typeof AuthenticatedPortalCreditRouteWithChildren
  '/_authenticated/portal/credit/verification': typeof AuthenticatedPortalCreditVerificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bankruptcy'
    | '/login'
    | '/signup'
    | '/portal'
    | '/portal/bankruptcy'
    | '/portal/credit'
    | '/portal/credit/verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bankruptcy'
    | '/login'
    | '/signup'
    | '/portal'
    | '/portal/bankruptcy'
    | '/portal/credit'
    | '/portal/credit/verification'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/bankruptcy'
    | '/login'
    | '/signup'
    | '/_authenticated/portal'
    | '/_authenticated/portal/bankruptcy'
    | '/_authenticated/portal/credit'
    | '/_authenticated/portal/credit/verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BankruptcyRoute: typeof BankruptcyRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bankruptcy': {
      id: '/bankruptcy'
      path: '/bankruptcy'
      fullPath: '/bankruptcy'
      preLoaderRoute: typeof BankruptcyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/credit': {
      id: '/_authenticated/portal/credit'
      path: '/credit'
      fullPath: '/portal/credit'
      preLoaderRoute: typeof AuthenticatedPortalCreditRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/bankruptcy': {
      id: '/_authenticated/portal/bankruptcy'
      path: '/bankruptcy'
      fullPath: '/portal/bankruptcy'
      preLoaderRoute: typeof AuthenticatedPortalBankruptcyRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/credit/verification': {
      id: '/_authenticated/portal/credit/verification'
      path: '/verification'
      fullPath: '/portal/credit/verification'
      preLoaderRoute: typeof AuthenticatedPortalCreditVerificationRouteImport
      parentRoute: typeof AuthenticatedPortalCreditRoute
    }
  }
}

interface AuthenticatedPortalCreditRouteChildren {
  AuthenticatedPortalCreditVerificationRoute: typeof AuthenticatedPortalCreditVerificationRoute
}

const AuthenticatedPortalCreditRouteChildren: AuthenticatedPortalCreditRouteChildren =
  {
    AuthenticatedPortalCreditVerificationRoute:
      AuthenticatedPortalCreditVerificationRoute,
  }

const AuthenticatedPortalCreditRouteWithChildren =
  AuthenticatedPortalCreditRoute._addFileChildren(
    AuthenticatedPortalCreditRouteChildren,
  )

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalBankruptcyRoute: typeof AuthenticatedPortalBankruptcyRoute
  AuthenticatedPortalCreditRoute: typeof AuthenticatedPortalCreditRouteWithChildren
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalBankruptcyRoute: AuthenticatedPortalBankruptcyRoute,
  AuthenticatedPortalCreditRoute: AuthenticatedPortalCreditRouteWithChildren,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BankruptcyRoute: BankruptcyRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
